### ISSUE TITLE
When updating doplarr it autofills "not_set_by_default" in JAVA_OPTS env variable causing container to throw an error and not load the bot.

### ISSUE THREAD

**Issue by bharvey88** [linuxserver/docker-doplarr#5]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When updating doplarr it autofills "not_set_by_default" in JAVA_OPTS env variable causing container to throw an error and not load the bot. deleting the environmental variable or removing the "not_set_by_default" line does not work because each update it returns.
------------------------------

## Expected Behavior

the environmental variable should either not be in the template or it should default to an empty box so it doesnt fail to load the container.
## Current Behavior

i update and a working container breaks until i manually delete the environmental variable or remove the "not_set_by_default" line 
## Steps to Reproduce

1.should not be necessary as information above is enough, but here it goes:
2.configure container and remove "not_set_by_default" or delete the JAVA_OPTS env variable, then container works.
3.update container and it no longer works because the env variable with the "not_set_by_default" line is back.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

unraid 6.9.2 installed from CA
## Docker logs

Caused by: java.lang.ClassNotFoundException: not_set_by_default
Error: Could not find or load main class not_set_by_default
Caused by: java.lang.ClassNotFoundException: not_set_by_default
Error: Could not find or load main class not_set_by_default
Caused by: java.lang.ClassNotFoundException: not_set_by_default
Error: Could not find or load main class not_set_by_default

this over and over and over^

**Comment by bharvey88** [comment]
@nemchik I might've made a bad suggestion above.. when leaving the template blank it still had the same errors in log and no joy with the bot coming online. Only removing the environmental variable brought it back up.

**Comment by nemchik** [comment]
I missed your comment before merging the PR, which closed this issue.

Leaving the variable blank should fix the issue. Removing the variable should also be fine. In my use of unraid, it seems inconsistent about when it adds variables back in after I have removed them.

The variable is used here:
https://github.com/linuxserver/docker-doplarr/blob/d502de44417f31aa3fb8c21e60cc9d7ab25d915d/root/etc/services.d/doplarr/run#L23
which ends up here:
https://github.com/linuxserver/docker-doplarr/blob/d502de44417f31aa3fb8c21e60cc9d7ab25d915d/root/etc/services.d/doplarr/run#L27-L30

**Comment by bharvey88** [comment]
I updated to latest and it's confirmed working as expected thanks!
